version: "3"
services:
   php:
     image: php:apache
     container_name: php
     ports:
       - "8000:80"
     volumes:
       - ./:/var/www/html
     links:
       - mariadb
     privileged: true
   mariadb:
     image: mariadb:10.1
     container_name: mariadb
     environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=m2l
     ports:
       - "8091:3306" 
   composer: 
     build: docker
     volumes:
      - ./:/var/www/html
     tty: true